(cl:defpackage lidar_msgs-msg
  (:use )
  (:export
   "<CENTROIDS>"
   "CENTROIDS"
   "<CLOUDCLUSTER>"
   "CLOUDCLUSTER"
   "<CLOUDCLUSTERARRAY>"
   "CLOUDCLUSTERARRAY"
   "<DETECTEDOBJECT>"
   "DETECTEDOBJECT"
   "<DETECTEDOBJECTARRAY>"
   "DETECTEDOBJECTARRAY"
   "<LIDAROBJECT>"
   "LIDAROBJECT"
   "<LIDAROBJECTLIST>"
   "LIDAROBJECTLIST"
   "<OBJFUSION>"
   "OBJFUSION"
   "<OBJLIST>"
   "OBJLIST"
   "<OBJLISTARRAY>"
   "OBJLISTARRAY"
  ))

