(cl:in-package lidar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          IS_OBJ-VAL
          IS_OBJ
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          CLOUD-VAL
          CLOUD
          CELLS-VAL
          CELLS
          CONVEX_HULL-VAL
          CONVEX_HULL
          POSE-VAL
          POSE
          DIMENSIONS-VAL
          DIMENSIONS
          ESTIMATED_ANGLE-VAL
          ESTIMATED_ANGLE
          MIN_POINT-VAL
          MIN_POINT
          MAX_POINT-VAL
          MAX_POINT
          AVG_POINT-VAL
          AVG_POINT
          CENTROID_POINT-VAL
          CENTROID_POINT
          EIGEN_VALUES-VAL
          EIGEN_VALUES
          EIGEN_VECTORS-VAL
          EIGEN_VECTORS
          FPFH_DESCRIPTOR-VAL
          FPFH_DESCRIPTOR
          INDICATOR_STATE-VAL
          INDICATOR_STATE
))