(cl:in-package lidar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          TYPE-VAL
          TYPE
          SCORE-VAL
          SCORE
          COLOR-VAL
          COLOR
          VALID-VAL
          VALID
          POSE-VAL
          POSE
          TRACKED_POSE-VAL
          TRACKED_POSE
          OUTPUT_POSE-VAL
          OUTPUT_POSE
          YAW-VAL
          YAW
          DIMENSIONS-VAL
          DIMENSIONS
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          ANGLE-VAL
          ANGLE
          BEHAVIOR_STATE-VAL
          BEHAVIOR_STATE
          AGE-VAL
          AGE
          VELOCITYSTATUS-VAL
          VELOCITYSTATUS
          CONFIDENCE-VAL
          CONFIDENCE
          POINTCLOUD-VAL
          POINTCLOUD
          CELLS-VAL
          CELLS
          CONVEX_HULL-VAL
          CONVEX_HULL
          POSE_RELIABLE-VAL
          POSE_RELIABLE
          VELOCITY_RELIABLE-VAL
          VELOCITY_RELIABLE
          ACCELERATION_RELIABLE-VAL
          ACCELERATION_RELIABLE
))