Header header
float64 AS_Veh_Acceleration_Value        # 惯导采集到的加速度
int16 AS_Driver_TakeOver_Req             # 驾驶员接管提醒(2B9)
float64 VCU_Accel_Pos_Value              # 实际加速踏板位置
float64 VCU_BrkPel_Pos_Value             # 实际制动踏板位置
float64 VCU_Real_Speed                   # 当前车速
int16 VCU_Current_Gear                   # 当前档位
int16 VCU_Parking_St                     # 当前P档位
int16 AutoD_Limitin_Reason               # 限制进入自动驾驶原因
int16 Emergency_Stop_Reason              # 紧急停车激活原因
int16 VCU_Driver_TakeOver_Req            # 驾驶员接管提醒(2BA)
int16 VCU_Vehicle_Drive_Mode_St          # 车辆驾驶模式
int16 AutoD_Out_Reason                   # 退出自动驾驶原因
int16 Brak_Sys_Fault_St                  # 制动系统故障
float64 Strg_Angle_Real_Value            # 方向盘实际转角
float64 Strg_Angle_Spd_Value             # 方向盘当前实际速度反馈
int16 Strg_WorkMode_St                   # 当前系统实际工作模式