# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from common_msgs/CICV_Location.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class CICV_Location(genpy.Message):
  _md5sum = "ebf8c055c1ba72efc55306e155279a03"
  _type = "common_msgs/CICV_Location"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header  header
float64 SimTim
float64 Position_x   #本车X向坐标
float64 Position_y   #本车Y向坐标
float64 Velocity_x   #本车X向车速
float64 Velocity_y   #本车Y向车速
float64 Accel_x      #本车纵向加速度
float64 Accel_y      #本车横向加速度
float64 Yaw          #本车航向角
float64 Angular_velocity_z    #本车沿Z轴角速度

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','SimTim','Position_x','Position_y','Velocity_x','Velocity_y','Accel_x','Accel_y','Yaw','Angular_velocity_z']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,SimTim,Position_x,Position_y,Velocity_x,Velocity_y,Accel_x,Accel_y,Yaw,Angular_velocity_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CICV_Location, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.SimTim is None:
        self.SimTim = 0.
      if self.Position_x is None:
        self.Position_x = 0.
      if self.Position_y is None:
        self.Position_y = 0.
      if self.Velocity_x is None:
        self.Velocity_x = 0.
      if self.Velocity_y is None:
        self.Velocity_y = 0.
      if self.Accel_x is None:
        self.Accel_x = 0.
      if self.Accel_y is None:
        self.Accel_y = 0.
      if self.Yaw is None:
        self.Yaw = 0.
      if self.Angular_velocity_z is None:
        self.Angular_velocity_z = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.SimTim = 0.
      self.Position_x = 0.
      self.Position_y = 0.
      self.Velocity_x = 0.
      self.Velocity_y = 0.
      self.Accel_x = 0.
      self.Accel_y = 0.
      self.Yaw = 0.
      self.Angular_velocity_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_9d().pack(_x.SimTim, _x.Position_x, _x.Position_y, _x.Velocity_x, _x.Velocity_y, _x.Accel_x, _x.Accel_y, _x.Yaw, _x.Angular_velocity_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.SimTim, _x.Position_x, _x.Position_y, _x.Velocity_x, _x.Velocity_y, _x.Accel_x, _x.Accel_y, _x.Yaw, _x.Angular_velocity_z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_9d().pack(_x.SimTim, _x.Position_x, _x.Position_y, _x.Velocity_x, _x.Velocity_y, _x.Accel_x, _x.Accel_y, _x.Yaw, _x.Angular_velocity_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.SimTim, _x.Position_x, _x.Position_y, _x.Velocity_x, _x.Velocity_y, _x.Accel_x, _x.Accel_y, _x.Yaw, _x.Angular_velocity_z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
