# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from common_msgs/DRPoseWithTime.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import common_msgs.msg

class DRPoseWithTime(genpy.Message):
  _md5sum = "e3866a48419eccf2d481c14a6c62e1f5"
  _type = "common_msgs/DRPoseWithTime"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32      week
float64    utctime
float64    dr_time
PoseEuler  pose_euler
================================================================================
MSG: common_msgs/PoseEuler
Vector3WithCovariance 	position
EulerWithCovariance 	rotation
================================================================================
MSG: common_msgs/Vector3WithCovariance
UnsureVar 	x
UnsureVar 	y
UnsureVar 	z
================================================================================
MSG: common_msgs/UnsureVar
float64 	variable
float64 	var_std
================================================================================
MSG: common_msgs/EulerWithCovariance
UnsureVar 	roll
UnsureVar 	pitch
UnsureVar 	yaw"""
  __slots__ = ['week','utctime','dr_time','pose_euler']
  _slot_types = ['int32','float64','float64','common_msgs/PoseEuler']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       week,utctime,dr_time,pose_euler

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DRPoseWithTime, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.week is None:
        self.week = 0
      if self.utctime is None:
        self.utctime = 0.
      if self.dr_time is None:
        self.dr_time = 0.
      if self.pose_euler is None:
        self.pose_euler = common_msgs.msg.PoseEuler()
    else:
      self.week = 0
      self.utctime = 0.
      self.dr_time = 0.
      self.pose_euler = common_msgs.msg.PoseEuler()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i14d().pack(_x.week, _x.utctime, _x.dr_time, _x.pose_euler.position.x.variable, _x.pose_euler.position.x.var_std, _x.pose_euler.position.y.variable, _x.pose_euler.position.y.var_std, _x.pose_euler.position.z.variable, _x.pose_euler.position.z.var_std, _x.pose_euler.rotation.roll.variable, _x.pose_euler.rotation.roll.var_std, _x.pose_euler.rotation.pitch.variable, _x.pose_euler.rotation.pitch.var_std, _x.pose_euler.rotation.yaw.variable, _x.pose_euler.rotation.yaw.var_std))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose_euler is None:
        self.pose_euler = common_msgs.msg.PoseEuler()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.week, _x.utctime, _x.dr_time, _x.pose_euler.position.x.variable, _x.pose_euler.position.x.var_std, _x.pose_euler.position.y.variable, _x.pose_euler.position.y.var_std, _x.pose_euler.position.z.variable, _x.pose_euler.position.z.var_std, _x.pose_euler.rotation.roll.variable, _x.pose_euler.rotation.roll.var_std, _x.pose_euler.rotation.pitch.variable, _x.pose_euler.rotation.pitch.var_std, _x.pose_euler.rotation.yaw.variable, _x.pose_euler.rotation.yaw.var_std,) = _get_struct_i14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i14d().pack(_x.week, _x.utctime, _x.dr_time, _x.pose_euler.position.x.variable, _x.pose_euler.position.x.var_std, _x.pose_euler.position.y.variable, _x.pose_euler.position.y.var_std, _x.pose_euler.position.z.variable, _x.pose_euler.position.z.var_std, _x.pose_euler.rotation.roll.variable, _x.pose_euler.rotation.roll.var_std, _x.pose_euler.rotation.pitch.variable, _x.pose_euler.rotation.pitch.var_std, _x.pose_euler.rotation.yaw.variable, _x.pose_euler.rotation.yaw.var_std))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose_euler is None:
        self.pose_euler = common_msgs.msg.PoseEuler()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.week, _x.utctime, _x.dr_time, _x.pose_euler.position.x.variable, _x.pose_euler.position.x.var_std, _x.pose_euler.position.y.variable, _x.pose_euler.position.y.var_std, _x.pose_euler.position.z.variable, _x.pose_euler.position.z.var_std, _x.pose_euler.rotation.roll.variable, _x.pose_euler.rotation.roll.var_std, _x.pose_euler.rotation.pitch.variable, _x.pose_euler.rotation.pitch.var_std, _x.pose_euler.rotation.yaw.variable, _x.pose_euler.rotation.yaw.var_std,) = _get_struct_i14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i14d = None
def _get_struct_i14d():
    global _struct_i14d
    if _struct_i14d is None:
        _struct_i14d = struct.Struct("<i14d")
    return _struct_i14d
