# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from common_msgs/PoseEuler.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import common_msgs.msg

class PoseEuler(genpy.Message):
  _md5sum = "d8f0dec34a7aced56ccf5b23f28c3a53"
  _type = "common_msgs/PoseEuler"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Vector3WithCovariance 	position
EulerWithCovariance 	rotation
================================================================================
MSG: common_msgs/Vector3WithCovariance
UnsureVar 	x
UnsureVar 	y
UnsureVar 	z
================================================================================
MSG: common_msgs/UnsureVar
float64 	variable
float64 	var_std
================================================================================
MSG: common_msgs/EulerWithCovariance
UnsureVar 	roll
UnsureVar 	pitch
UnsureVar 	yaw"""
  __slots__ = ['position','rotation']
  _slot_types = ['common_msgs/Vector3WithCovariance','common_msgs/EulerWithCovariance']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,rotation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseEuler, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = common_msgs.msg.Vector3WithCovariance()
      if self.rotation is None:
        self.rotation = common_msgs.msg.EulerWithCovariance()
    else:
      self.position = common_msgs.msg.Vector3WithCovariance()
      self.rotation = common_msgs.msg.EulerWithCovariance()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.position.x.variable, _x.position.x.var_std, _x.position.y.variable, _x.position.y.var_std, _x.position.z.variable, _x.position.z.var_std, _x.rotation.roll.variable, _x.rotation.roll.var_std, _x.rotation.pitch.variable, _x.rotation.pitch.var_std, _x.rotation.yaw.variable, _x.rotation.yaw.var_std))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = common_msgs.msg.Vector3WithCovariance()
      if self.rotation is None:
        self.rotation = common_msgs.msg.EulerWithCovariance()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.position.x.variable, _x.position.x.var_std, _x.position.y.variable, _x.position.y.var_std, _x.position.z.variable, _x.position.z.var_std, _x.rotation.roll.variable, _x.rotation.roll.var_std, _x.rotation.pitch.variable, _x.rotation.pitch.var_std, _x.rotation.yaw.variable, _x.rotation.yaw.var_std,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.position.x.variable, _x.position.x.var_std, _x.position.y.variable, _x.position.y.var_std, _x.position.z.variable, _x.position.z.var_std, _x.rotation.roll.variable, _x.rotation.roll.var_std, _x.rotation.pitch.variable, _x.rotation.pitch.var_std, _x.rotation.yaw.variable, _x.rotation.yaw.var_std))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = common_msgs.msg.Vector3WithCovariance()
      if self.rotation is None:
        self.rotation = common_msgs.msg.EulerWithCovariance()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.position.x.variable, _x.position.x.var_std, _x.position.y.variable, _x.position.y.var_std, _x.position.z.variable, _x.position.z.var_std, _x.rotation.roll.variable, _x.rotation.roll.var_std, _x.rotation.pitch.variable, _x.rotation.pitch.var_std, _x.rotation.yaw.variable, _x.rotation.yaw.var_std,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
