// Generated by gencpp from file navi_msgs/StationPoint.msg
// DO NOT EDIT!


#ifndef NAVI_MSGS_MESSAGE_STATIONPOINT_H
#define NAVI_MSGS_MESSAGE_STATIONPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navi_msgs
{
template <class ContainerAllocator>
struct StationPoint_
{
  typedef StationPoint_<ContainerAllocator> Type;

  StationPoint_()
    : x(0.0)
    , y(0.0)
    , station_id(0)  {
    }
  StationPoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , station_id(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef uint16_t _station_id_type;
  _station_id_type station_id;





  typedef boost::shared_ptr< ::navi_msgs::StationPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navi_msgs::StationPoint_<ContainerAllocator> const> ConstPtr;

}; // struct StationPoint_

typedef ::navi_msgs::StationPoint_<std::allocator<void> > StationPoint;

typedef boost::shared_ptr< ::navi_msgs::StationPoint > StationPointPtr;
typedef boost::shared_ptr< ::navi_msgs::StationPoint const> StationPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navi_msgs::StationPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navi_msgs::StationPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navi_msgs::StationPoint_<ContainerAllocator1> & lhs, const ::navi_msgs::StationPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.station_id == rhs.station_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navi_msgs::StationPoint_<ContainerAllocator1> & lhs, const ::navi_msgs::StationPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navi_msgs::StationPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navi_msgs::StationPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navi_msgs::StationPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navi_msgs::StationPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navi_msgs::StationPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navi_msgs::StationPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navi_msgs::StationPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd87fa514ed6a37f6daab224ce9b0919";
  }

  static const char* value(const ::navi_msgs::StationPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd87fa514ed6a37fULL;
  static const uint64_t static_value2 = 0x6daab224ce9b0919ULL;
};

template<class ContainerAllocator>
struct DataType< ::navi_msgs::StationPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navi_msgs/StationPoint";
  }

  static const char* value(const ::navi_msgs::StationPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navi_msgs::StationPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"uint16 station_id\n"
;
  }

  static const char* value(const ::navi_msgs::StationPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navi_msgs::StationPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.station_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StationPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navi_msgs::StationPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navi_msgs::StationPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "station_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.station_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVI_MSGS_MESSAGE_STATIONPOINT_H
