// Generated by gencpp from file navi_msgs/TimeStamp.msg
// DO NOT EDIT!


#ifndef NAVI_MSGS_MESSAGE_TIMESTAMP_H
#define NAVI_MSGS_MESSAGE_TIMESTAMP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navi_msgs
{
template <class ContainerAllocator>
struct TimeStamp_
{
  typedef TimeStamp_<ContainerAllocator> Type;

  TimeStamp_()
    : s(0)
    , ns(0)  {
    }
  TimeStamp_(const ContainerAllocator& _alloc)
    : s(0)
    , ns(0)  {
  (void)_alloc;
    }



   typedef uint64_t _s_type;
  _s_type s;

   typedef uint64_t _ns_type;
  _ns_type ns;





  typedef boost::shared_ptr< ::navi_msgs::TimeStamp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navi_msgs::TimeStamp_<ContainerAllocator> const> ConstPtr;

}; // struct TimeStamp_

typedef ::navi_msgs::TimeStamp_<std::allocator<void> > TimeStamp;

typedef boost::shared_ptr< ::navi_msgs::TimeStamp > TimeStampPtr;
typedef boost::shared_ptr< ::navi_msgs::TimeStamp const> TimeStampConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navi_msgs::TimeStamp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navi_msgs::TimeStamp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navi_msgs::TimeStamp_<ContainerAllocator1> & lhs, const ::navi_msgs::TimeStamp_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s &&
    lhs.ns == rhs.ns;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navi_msgs::TimeStamp_<ContainerAllocator1> & lhs, const ::navi_msgs::TimeStamp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navi_msgs::TimeStamp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navi_msgs::TimeStamp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navi_msgs::TimeStamp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navi_msgs::TimeStamp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navi_msgs::TimeStamp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navi_msgs::TimeStamp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navi_msgs::TimeStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "239b6a0a87ff2c711f5fde0f2b68a67d";
  }

  static const char* value(const ::navi_msgs::TimeStamp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x239b6a0a87ff2c71ULL;
  static const uint64_t static_value2 = 0x1f5fde0f2b68a67dULL;
};

template<class ContainerAllocator>
struct DataType< ::navi_msgs::TimeStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navi_msgs/TimeStamp";
  }

  static const char* value(const ::navi_msgs::TimeStamp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navi_msgs::TimeStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 s\n"
"uint64 ns\n"
;
  }

  static const char* value(const ::navi_msgs::TimeStamp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navi_msgs::TimeStamp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.ns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeStamp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navi_msgs::TimeStamp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navi_msgs::TimeStamp_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.s);
    s << indent << "ns: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.ns);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVI_MSGS_MESSAGE_TIMESTAMP_H
