(cl:in-package common_msgs-msg)
(cl:export '(SIMTIM-VAL
          SIMTIM
          ID-VAL
          ID
          X-VAL
          X
          Y-VAL
          Y
          V_X-VAL
          V_X
          V_Y-VAL
          V_Y
          XG-VAL
          XG
          YG-VAL
          YG
          V_XG-VAL
          V_XG
          V_YG-VAL
          V_YG
          HEADING-VAL
          HEADING
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          TYPE-VAL
          TYPE
          XREL-VAL
          XREL
          YREL-VAL
          YREL
          V_XREL-VAL
          V_XREL
          V_YREL-VAL
          V_YREL
))