(cl:in-package perception_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FRAME_UNMBER-VAL
          FRAME_UNMBER
          FUSION_LEVEL-VAL
          FUSION_LEVEL
          STATUS-VAL
          STATUS
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ROLL_STD-VAL
          ROLL_STD
          PITCH_STD-VAL
          PITCH_STD
          YAW_STD-VAL
          YAW_STD
          QW-VAL
          QW
          QX-VAL
          QX
          QY-VAL
          QY
          QZ-VAL
          QZ
          ANGULAR_VELOCITY_X-VAL
          ANGULAR_VELOCITY_X
          ANGULAR_VELOCITY_Y-VAL
          ANGULAR_VELOCITY_Y
          ANGULAR_VELOCITY_Z-VAL
          ANGULAR_VELOCITY_Z
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          LATITUDE_STD-VAL
          LATITUDE_STD
          LONGITUDE_STD-VAL
          LONGITUDE_STD
          ALTITUDE_STD-VAL
          ALTITUDE_STD
          POSITION_X-VAL
          POSITION_X
          POSITION_Y-VAL
          POSITION_Y
          POSITION_Z-VAL
          POSITION_Z
          POSITION_X_STD-VAL
          POSITION_X_STD
          POSITION_Y_STD-VAL
          POSITION_Y_STD
          POSITION_Z_STD-VAL
          POSITION_Z_STD
          VELOCITY_X-VAL
          VELOCITY_X
          VELOCITY_Y-VAL
          VELOCITY_Y
          VELOCITY_Z-VAL
          VELOCITY_Z
          VELOCITY_X_STD-VAL
          VELOCITY_X_STD
          VELOCITY_Y_STD-VAL
          VELOCITY_Y_STD
          VELOCITY_Z_STD-VAL
          VELOCITY_Z_STD
          VELOCITY_RX-VAL
          VELOCITY_RX
          VELOCITY_RY-VAL
          VELOCITY_RY
          VELOCITY_RZ-VAL
          VELOCITY_RZ
          VELOCITY_RX_STD-VAL
          VELOCITY_RX_STD
          VELOCITY_RY_STD-VAL
          VELOCITY_RY_STD
          VELOCITY_RZ_STD-VAL
          VELOCITY_RZ_STD
          ACCEL_X-VAL
          ACCEL_X
          ACCEL_Y-VAL
          ACCEL_Y
          ACCEL_Z-VAL
          ACCEL_Z
))