(cl:in-package perception_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          IS_INVALID-VAL
          IS_INVALID
          IS_MATCHED-VAL
          IS_MATCHED
          IS_STILL-VAL
          IS_STILL
          CLUSTER_MASK-VAL
          CLUSTER_MASK
          RADAR_ID-VAL
          RADAR_ID
          OBJECT_ID-VAL
          OBJECT_ID
          TYPE-VAL
          TYPE
          LIFE_COUNT-VAL
          LIFE_COUNT
          RCS-VAL
          RCS
          CONFIDENCE-VAL
          CONFIDENCE
          AZIMUTH-VAL
          AZIMUTH
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          DIMENSIONS-VAL
          DIMENSIONS
))