(cl:in-package perception_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          OBJECT_ID-VAL
          OBJECT_ID
          TYPE-VAL
          TYPE
          DETECT_CONFIDENCE-VAL
          DETECT_CONFIDENCE
          TYPE_CONFIDENCE-VAL
          TYPE_CONFIDENCE
          DIMENSIONS-VAL
          DIMENSIONS
          CLUSTER_POSE-VAL
          CLUSTER_POSE
          TRACKED_POSE-VAL
          TRACKED_POSE
          CLUSTER_YAW-VAL
          CLUSTER_YAW
          TRACKED_YAW-VAL
          TRACKED_YAW
          AZIMUTH-VAL
          AZIMUTH
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          TRACKING_STATE-VAL
          TRACKING_STATE
          CELLS-VAL
          CELLS
))