(cl:in-package perception_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SENSOR_ID-VAL
          SENSOR_ID
          OBJECT_ID-VAL
          OBJECT_ID
          DETECT_CONFIDENCE-VAL
          DETECT_CONFIDENCE
          TYPE_CONFIDENCE-VAL
          TYPE_CONFIDENCE
          AZIMUTH-VAL
          AZIMUTH
          YAW-VAL
          YAW
          TYPE-VAL
          TYPE
          TRACKING_TIME-VAL
          TRACKING_TIME
          TRACKING_LEVEL-VAL
          TRACKING_LEVEL
          LANE_ASSIGNMENT-VAL
          LANE_ASSIGNMENT
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          DIMENSIONS-VAL
          DIMENSIONS
          PIXEL_CENTRAL_POINT-VAL
          PIXEL_CENTRAL_POINT
          PIXEL_BOX_SIZE-VAL
          PIXEL_BOX_SIZE
))