(cl:in-package perception_msgs-msg)
(cl:export '(ID-VAL
          ID
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          VXREL-VAL
          VXREL
          VYREL-VAL
          VYREL
          XABS-VAL
          XABS
          YABS-VAL
          YABS
          VXABS-VAL
          VXABS
          VYABS-VAL
          VYABS
          WIDTH-VAL
          WIDTH
          LENGTH-VAL
          LENGTH
          HEIGHT-VAL
          HEIGHT
          SPEED-VAL
          SPEED
          HEADING-VAL
          HEADING
          TYPE-VAL
          TYPE
          SOURCE-VAL
          SOURCE
          CONFIDENCE-VAL
          CONFIDENCE
          AGE-VAL
          AGE
          VELOCITYSTATUS-VAL
          VELOCITYSTATUS
          CELLS-VAL
          CELLS
))