(cl:in-package canbus_msgs-msg)
(cl:export '(CAN_FAULT_FLAG-VAL
          CAN_FAULT_FLAG
          CAN103_FAULT_FLAG-VAL
          CAN103_FAULT_FLAG
          MMW_LIDAR0_FLAG-VAL
          MMW_LIDAR0_FLAG
          MMW_LIDAR1_FLAG-VAL
          MMW_LIDAR1_FLAG
          MMW_LIDAR3_FLAG-VAL
          MMW_LIDAR3_FLAG
          MMW_LIDAR5_FLAG-VAL
          MMW_LIDAR5_FLAG
          MMW_LIDAR7_FLAG-VAL
          MMW_LIDAR7_FLAG
          ULT_5C8_FLAG-VAL
          ULT_5C8_FLAG
          ULT_5C9_FLAG-VAL
          ULT_5C9_FLAG
          CAN_BUSOFF_FLAG-VAL
          CAN_BUSOFF_FLAG
          CAN103_BUSOFF_FLAG-VAL
          CAN103_BUSOFF_FLAG
          CANBUS_MODULE_LEVEL1_FLAG-VAL
          CANBUS_MODULE_LEVEL1_FLAG
          CANBUS_MODULE_LEVEL2_FLAG-VAL
          CANBUS_MODULE_LEVEL2_FLAG
))