
Header header

uint64 frame_unmber
int8 fusion_level
int8 status
float64 gyro_x      # R, car body (RFU)
float64 gyro_y      # R, car body (RFU)
float64 gyro_z      # R, car body (RFU)
float64 accel_x     # R, car body (RFU)
float64 accel_y     # F, car body (RFU)
float64 accel_z     # U, car body (RFU)
float64 q0          # 
float64 q1
float64 q2
float64 q3
float32 yaw         # utm (0,360)  0--east, 90--north
float64 position_x  # utm_east
float64 position_y  # utm_north
float64 position_z  # utm_up
float64 velocity_x  # utm_east
float64 velocity_y  # utm_north
float64 velocity_z  # utm_up



